### ISSUE TITLE
Question: Can I invoke setValue on search-select component from Observable completion handler?

### ISSUE THREAD

**Issue by jrmihalick** [OasisDigital/angular-material-search-select#10]
I have a component which has a search-select component as a child and in the ngOnInit for my component, I am initializing the datasource of the search-select.  I want to programmatically set the selected value in the search-select once I have loaded all of my data from the external data source.  I have tested setting the value in the search-select from a button click and it works just fine, but I have been unable to successfully set the value from  either ngOnInit or ngAfterViewInit of my component via a **completion handler that I set up on the observable that is supplying my data**.  Is there a known issue with this or an alternate way for me to set the value programatically? In my case, I can't set the value triggered on an event from the user, the selected value is coming from the server.

In the code below, this.formField is an object with metadata about the FormControl (such as the id of the control, the value that should be selected, etc.) and in this case the FormControl is the search-select component bound via a formControlName directive.  All other aspects of our use of the search-select are working fine, it's just this one problem of setting the select value upon initialization that is causing us problems

```
  updateAutoCompleteDataSource() {
    this.valuesSubscription = this.screenService.getFieldValues(this.formField.id).subscribe((data) => {
      const values: Array<string> = data;
      const fld = this.formField;
      console.log('asynchronously received ' + values.length + ' items for ' + fld.id);
      
      this.autoCompleteDataSource = {
        displayValue(value: any): Observable<OptionEntry | null> {
          console.log(`being asked to display value for: ${value}`);
          const display = <string>value;
          return of({
            value,
            display,
            details: {}
          });
        },

        search(term: string): Observable<OptionEntry[]> {
          console.log(`autocomplete searching for '${term}' on field '${fld.id}' with ${values.length} values`);
          const lowerTerm = typeof term === 'string' ? term.toLowerCase() : '';
          return of(values
            .filter((c: any) => c.toLowerCase().indexOf(lowerTerm) >= 0)
            .slice(0, 1000).map((v: any) => ({
              value: v,
              display: v,
              details: {}
            })));
        }
      };
    },
    (error) => {},
    () => {
      console.log(`Attempting to set value of '${this.formField.value}' on field '${this.formField.id}'`);
      this.formGroup.get(this.formField.id).setValue(this.formField.value);
    }
  );
  }
```

In the completion handler of the Observable above, I am attempting to set the value. Thanks for your review.

**Comment by kylecordes** [comment]
@jrmihalick Looking at your code and description, it seems to first that it can be simplified. You have written code here where you create a subscription to get data, then use that to set up the search select data source. The simplification would be: don't perform that outer subscription yourself, rather implement the necessary data fetch code inside the data source functions. That way the subscriptions we managed automatically also.

Now onto the more specific question about the setValue. There's no reason this would not work; in our code that uses the search-select, we routinely use setValue(). If you implement the mechanism of the described above, you also don't need to worry about the timing of which thing happens "first". You can set the value as soon as you like, and then when the data flows through the observables the search select code will do the right thing.

Is it possible you could re-create a small example of what you are trying to do, in a StackBlitz? If you can reproduce a problem there I could possibly help better.

**Comment by jrmihalick** [comment]
@kylecordes Thank you sir!  I made the adjustments as you suggested and it is working fine now.  Revised code shown below.  I slightly tweaked our web service to allow passing in of a search term parameter so that we could use your search-select as it was intended.  I then put the call to setValue in ngAfterViewInit and it's working great.

```
updateAutoCompleteDataSource2() {
    const fld: IFormElement = this.formField;
    const scrnSvc: ScreenService = this.screenService;
    this.autoCompleteDataSource = {
      displayValue(value: any): Observable<OptionEntry | null> {
        console.log(`being asked to display value for: ${value}`);
        const display = <string>value;
        return of({
          value,
          display,
          details: {}
        });
      },

      search(term: string): Observable<OptionEntry[]> {
        const lowerTerm = term ? term.toLowerCase() : '';
        console.log(`autocomplete searching for '${lowerTerm}' on field '${fld.id}'`);
        return (<Observable<Array<string>>> scrnSvc.getFieldValues(fld.id, lowerTerm))
          .pipe(
            map(searchResults => searchResults.slice(0, 1000).map(v => ({
              value: v,
              display: v,
              details: {}
            })))
          );
      }
    };

  }
```

**Comment by kylecordes** [comment]
@jrmihalick Here's a further tip. The code `slice(0, 1000)` is performing a length limit in your client-side code. That means that, if your list is very long (or for a search term that returns a very long list), your server code will generate a very long list, and then there will be a delay transferring this long list of the client. If your data is large, it is more ideal to perform this length-limit function as part of your server code, and ideally, inside your data store (database etc).

**Comment by jrmihalick** [comment]
Thanks @kylecordes.  I am aware of that issue.  This code will not be in place long term.  We are trying to get a product to pilot and will be making refinements to searching in a subsequent release.  The length slice is a band-aid for now and it will be removed later.
