### ISSUE TITLE
Make compatible with @angular/material version 6

### ISSUE THREAD

**Issue by espeandr** [OasisDigital/angular-material-search-select#12]
running `ng update @angular/material` on a angular material 5 project will give error:

> Package "angular-material-obs-autocomplete" has an incompatible peer dependency to "@angular/material" (requires "^5.0.1", would install "6.0.1").

**Comment by kylecordes** [comment]
I have encountered the same behavior with "ng update" myself on my own projects. It's not related to this library (search select), rather the challenges that "ng update" does not understand the idea that sometimes **other** libraries will have to be upgraded to become compatible with the library being updated. Hopefully a future improvement to "ng update" will understand this.
