### ISSUE TITLE
Regarding Search select with real (remote) API data

### ISSUE THREAD

**Issue by sandyJ1** [OasisDigital/angular-material-search-select#13]
Thanks for useful demo.

I need Out Put Like below
AccountName
PrimaryPhone EmailAddress

I want to Break the line after first field how toimplement.

I am using the same code then output shown below.

search(term: string): Observable<OptionEntry[]> {
        console.log('searching for', term);
        return http.get<Account[]>(apiURL, {
          params: {
            q: term || '',
            _sort: 'AccountName,EmailAddress'
          }
        }).pipe(
          map(list => list.map(e => ({
            value: e.AccountID,
          display: `${e.accountName}${e.primaryPhone }(${e.emailAddress})`,
                    details: {}
          }))));
      }
    };

Current Out Put :
AccountName PrimaryPhone EmailAddress

Please help me for this.

**Comment by sandyJ1** [comment]
Hi Kyle ,
<br> not working here.....!!!

**Comment by kylecordes** [comment]
@sandyJ1 Can you make an example of the problem you are having, on StackBlitz?  It should be just a smallest example of the problem, not your entire "real" application.

**Comment by kylecordes** [comment]
(If anyone experiences a problem like this, please open a new issue with an example that reproduces it!)
