### ISSUE TITLE
'formControl' isnt't a known property of 'search-select'

### ISSUE THREAD

**Issue by JoaoPortella** [OasisDigital/angular-material-search-select#15]
Hi

Angular version 6.1.0

I'm get this error when try to build an App with your demo-3-real-api example.

Some idea?

Thank's

**Comment by kylecordes** [comment]
First thing to try: make sure you include FormsModule and/or ReactiveFormsModule in your app module.

**Comment by JoaoPortella** [comment]
Yes, sorry. I just read the answer # 4.
Now everything work fine, thanks
