### ISSUE TITLE
Trigger displayValue without using FormControl

### ISSUE THREAD

**Issue by danger89** [OasisDigital/angular-material-search-select#9]
I know you can set a new (default) value via the formControl reactive forms. 

By creating a new FormControl:
```js
ours = new FormControl(...);
```

And set the value via:
```js
this.ours.setValue(3);
```

But since I don't want to provide any `input` element for the end-user to set a value, but rather my components knows which is the current value to set as default (retrieved from the database), I have the feeling this FormControl is overkill for me.

Is there another way to trigger `displayValue(..)` without using FormControl?

Thanks in advance.

Kind regards,
Melroy

**Comment by danger89** [comment]
Nevermind, I think this is how Angular just works..

**Comment by kylecordes** [comment]
Yes, that's correct. This is just the Angular API for setting up a form control value, nothing specific to this search and select widget.

**Comment by danger89** [comment]
Exactly. And since you are using [ControlValueAccessor](https://github.com/OasisDigital/angular-material-search-select/blob/master/src/app/search-select/base.ts#L27), you can just use the 2 way binding on your component/module by using the `[(ngModel)]` attribute.

Like so:
```
<search-select
  placeholder="Debit Ledger account"
  width="100%"
  debounceTime="400"
  [dataSource]="ledgerSearchSource"
  [formControl]="debitControl"
  [(ngModel)]="journal.journal_ledger_debit_id"></search-select>
```

Which is actually not explained (or I miss a demo). Maybe just once again, add an usage :+1:  somewhere -->
https://github.com/OasisDigital/angular-material-search-select

**Comment by kylecordes** [comment]
@danger89 As you point out it is possible to use both reactive forms and template forms with ngModel, but we don't recommend that here so we definitely don't show it in any example code. (Actually, we rarely used template forms at all.)

The control being bound to is not a search control, so I don't believe a `SelectControlValueAccessor` would be correct.

**Comment by danger89** [comment]
Thanks I will read:
https://expressjs.com/en/advanced/best-practice-performance.html
